"""
Calculate the regret of a bandit algorithm.
"""
import numpy as np

class Regret:
    def compute(self):
        raise NotImplementedError("Subclasses must implement this method")
    
class StochasticRegret(Regret):
    def compute(self, mean_rewards: list, chosen_arms: list) -> np.ndarray:
        """
        Args:
            mean_rewards: [K] array of mean rewards for each arm.
            chosen_arms: [T] array of arms chosen by the algorithm at each time step.
        return:
            cumulative_regret: [T] array of cumulative regret at each time step.
        """
        max_mean = max(mean_rewards) # Optimal mean reward
        per_step_regret = np.array([max_mean - mean_rewards[arm] for arm in chosen_arms]) # Per step regret
        cumulative_regret = np.cumsum(per_step_regret) # Cumulative regret at each time step
        return cumulative_regret
    
class AdversarialRegret(Regret):
    """
    Calculate the pseudo-regret for adversarial environment.
    This is based on the definition of pseudo-regret given in the book "Bandit Algorithms" by Lattimore and Szepesvari.
    """
    def compute(self, arm_probs: list[list], reward_matrix: list[list]) -> np.ndarray:
        """
        Args:
            arm_probs: [T x K] array of probabilities over arms for entire horizon.
            reward_matrix: [T x K] array of rewards generated by the adversary for each arm for entire horizon.
        return:
            cumulative_regret: [T] array of cumulative pseudo-regret at each time step.
        """
        # Cumulative rewards for each arm at each time step
        rewards_cumsum = np.cumsum(reward_matrix, axis=0)
        # Optimal arm in hindsight at each time step
        optimal_cumsum = np.max(rewards_cumsum, axis=1)
        # Expected reward of the algorithm at each time step
        expected_rewards = np.array([np.dot(prob, rewards) for prob, rewards in zip(arm_probs, reward_matrix)])
        expected_cum_rewards = np.cumsum(expected_rewards) 
        # Cumulative expected reward of the algorithm at each time step
        regret = optimal_cumsum - expected_cum_rewards
        return regret